export const projects = [
  {
    title: 'Transfer Ether & NFTs',
    description: "Web3 application used to transfer Ethereum or NFTs to any wallet address. App features two Solidity smart contracts that post information directly to the blockchain. Incorporated logic to query all recent transactions from the blockchain and display them in a section of the application.",
    image: '/images/EtherTransfer.png',
    tags: ['Solidity', 'Javascript', 'Web3.js', 'Vite'],
    source: 'https://ether-nft-transfer.netlify.app/',
    visit: 'https://github.com/daenamcclintock/Web3_Ethereum_NFT_Transfer_App',
    id: 3,
  },
  {
    title: 'LuxEstate',
    description: "Luxury real estate application designed for realtors to list properties and users to browse and inquire about properties. LuxEstate features two different user types, full CRUD functionality, and complex logic for searching and filtering properties by location as well as a multitude of metrics. Utilizing the MapBox API for visual mapping.",
    image: '/images/LuxEstate.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://github.com/daenamcclintock/Project-4-Client',
    id: 0,
  },
  {
    title: 'GytShop',
    description:"Full-stack e-commerce store featuring user authentication, full CRUD functionality, and the ability for users to add products to their cart and checkout. Built a proprietary API to seed data and utilized the third party Stripe API for payment processing. Developed in a team of four in three business days using Agile development methodology.",
    image: '/images/Gytshop.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'www.google.com',
    // source: 'https://gogytshop.herokuapp.com/',
    visit: 'https://github.com/daenamcclintock/GytShop-Client',
    id: 1,
  },
  {
    title: 'NFT Social',
    description: "Social media application designed for NFT owners to showcase their digital artwork. Application features secure user authentication and full CRUD functionality. Utilized the Moralis third party API to integrate search functionality and extract real-time data from the OpenSea NFT marketplace.",
    image: '/images/NFT_Social.png',
    tags: ['Liquid', 'Express', 'Mongo', 'Node'],
    source: 'www.google.com',
    // source: 'https://nftsocialmedia.herokuapp.com/',
    visit: 'https://github.com/daenamcclintock/NFT_Social',
    id: 2,
  },
  {
    title: 'Bringing Down The House!',
    description: "Interactive front-end blackjack game. Operates with logic mirroring casino-style blackjack and an AI simulating the dealer. Includes functionality to keep the card count and teach the user how to count cards. Individually developed over three business days.",
    image: 'https://static.turbosquid.com/Preview/2019/10/06__01_42_32/1.png86A9EB7C-E95E-431F-81C3-4FDD3D775C6ALarge.jpg',
    tags: ['Javascript', 'HTML', 'CSS', 'Bootstrap'],
    source: 'https://google.com',
    visit: 'https://github.com/daenamcclintock/bringing-down-the-house',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 'Summer 2019', text: "Interned with BNY Mellon's Buyside Equity Research Division", },
  { year: 'Spring 2020', text: "Graduated from UMass Amherst Cum Laude with Degrees in Finance and Economics", },
  { year: '2020/ 2021', text: "Worked for BNY Mellon Wealth Management in a Client-Facing Portfolio Analyst Role", },
  { year: 'Spring 2022', text: "Completed General Assembly's Software Engineering Immersive Program" },
  { year: 'Summer 2022', text: "Working on Several Web3 Projects: NFT Art Generation, Minting, and dApp Development ", },
];